"""sqlglot validator: one SELECT, allowlisted tables/columns, no comments, LIMIT injected."""
from __future__ import annotations

from dataclasses import dataclass

import sqlglot
from sqlglot import exp
from sqlglot.errors import SqlglotError

from sqltool.schema import (
    ALL_ALLOWED_COLUMNS, ALLOWED_SCHEMA, BLOCKED_COLUMNS, FORBIDDEN_TABLE_NAMES, MAX_ROWS, MAX_SQL_CHARS,
)

BLOCKED_FUNCTIONS = frozenset({
    "load_extension", "readfile", "writefile", "edit", "fts3_tokenizer",
    "zeroblob", "randomblob", "sqlite_source_id",
})


class SqlRejected(ValueError):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(f"{code}: {message}")
        self.code = code
        self.message = message


@dataclass(frozen=True)
class ValidatedSql:
    sql: str                  # regenerated by sqlglot; this is what gets executed
    tables: tuple[str, ...]


def validate_sql(sql: str, max_rows: int = MAX_ROWS) -> ValidatedSql:
    text = sql.strip()
    if not text:
        raise SqlRejected("empty", "no SQL provided")
    if len(text) > MAX_SQL_CHARS:
        raise SqlRejected("too_long", f"SQL longer than {MAX_SQL_CHARS} characters")
    if "--" in text or "/*" in text or "*/" in text:
        raise SqlRejected("comments", "SQL comments are not allowed")
    body = text[:-1].rstrip() if text.endswith(";") else text
    if ";" in body:
        raise SqlRejected("multi_statement", "only one statement is allowed")
    try:
        statements = [s for s in sqlglot.parse(body, read="sqlite") if s is not None]
    except SqlglotError as exc:
        raise SqlRejected("parse_error", str(exc).splitlines()[0]) from exc
    if len(statements) != 1:
        raise SqlRejected("multi_statement" if statements else "empty", "expected exactly one statement")
    tree = statements[0]
    if not isinstance(tree, exp.Select):
        raise SqlRejected("not_select", f"only a single SELECT is allowed (got {type(tree).__name__})")
    if any(w.args.get("recursive") for w in tree.find_all(exp.With)):
        raise SqlRejected("recursive", "WITH RECURSIVE is not allowed")
    if tree.find(exp.Placeholder, exp.Parameter) is not None:
        raise SqlRejected("placeholder", "query parameters are not allowed")

    tables = _check_tables(tree)
    _check_star(tree)
    _check_columns(tree)
    _check_functions(tree)
    tree = _enforce_limit(tree, max_rows)
    return ValidatedSql(sql=tree.sql(dialect="sqlite"), tables=tables)


def _check_tables(tree: exp.Select) -> tuple[str, ...]:
    cte_names = {c.alias_or_name.lower() for c in tree.find_all(exp.CTE)}
    for name in cte_names:
        if name in ALLOWED_SCHEMA or name in FORBIDDEN_TABLE_NAMES:
            raise SqlRejected("forbidden_table", f"CTE name '{name}' clashes with a table name")
    used: list[str] = []
    for table in tree.find_all(exp.Table):
        name = table.name.lower()
        if table.db or table.catalog:
            raise SqlRejected("forbidden_table", "schema-qualified tables are not allowed")
        if name in cte_names:
            continue
        if name not in ALLOWED_SCHEMA:
            raise SqlRejected("forbidden_table", f"table '{name or '<expression>'}' is not available")
        used.append(name)
    return tuple(dict.fromkeys(used))


def _check_star(tree: exp.Select) -> None:
    for star in tree.find_all(exp.Star):
        if not isinstance(star.parent, exp.Count):
            raise SqlRejected("star", "SELECT * is not allowed; list the columns explicitly")


def _check_columns(tree: exp.Select) -> None:
    aliases = {a.alias.lower() for a in tree.find_all(exp.Alias) if a.alias}
    for ta in tree.find_all(exp.TableAlias):
        aliases.update(c.name.lower() for c in ta.columns)
    for alias in aliases:
        if alias in BLOCKED_COLUMNS:
            raise SqlRejected("forbidden_column", f"alias '{alias}' is not allowed")
    for col in tree.find_all(exp.Column):
        name = col.name.lower()
        if name in BLOCKED_COLUMNS or (name not in ALL_ALLOWED_COLUMNS and name not in aliases):
            raise SqlRejected("forbidden_column", f"column '{name}' is not available")


def _check_functions(tree: exp.Select) -> None:
    for func in tree.find_all(exp.Func):
        name = (func.name if isinstance(func, exp.Anonymous) else func.sql_name()).lower()
        if name in BLOCKED_FUNCTIONS:
            raise SqlRejected("forbidden_function", f"function '{name}' is not allowed")


def _enforce_limit(tree: exp.Select, max_rows: int) -> exp.Select:
    limit = tree.args.get("limit")
    if limit is not None:
        lit = limit.args.get("expression")
        if isinstance(lit, exp.Literal) and lit.is_int and int(lit.name) <= max_rows:
            return tree
    # max_rows + 1 lets the executor detect truncation exactly
    return tree.limit(max_rows + 1)